[ { Name: 'Sand Crawler',
          Model: 'Digger Crawler',
          Class: 'wheeled',
          Passengers: '30' },
        { Name: 'T-16 skyhopper',
          Model: 'T-16 skyhopper',
          Class: 'repulsorcraft',
          Passengers: '1' },
        { Name: 'X-34 landspeeder',
          Model: 'X-34 landspeeder',
          Class: 'repulsorcraft',
          Passengers: '1' },
        { Name: 'TIE/LN starfighter',
          Model: 'Twin Ion Engine/Ln Starfighter',
          Class: 'starfighter',
          Passengers: '0' },
        { Name: 'Snowspeeder',
          Model: 't-47 airspeeder',
          Class: 'airspeeder',
          Passengers: '0' },
        { Name: 'TIE bomber',
          Model: 'TIE/sa bomber',
          Class: 'space/planetary bomber',
          Passengers: '0' },
        { Name: 'AT-AT',
          Model: 'All Terrain Armored Transport',
          Class: 'assault walker',
          Passengers: '40' },
        { Name: 'AT-ST',
          Model: 'All Terrain Scout Transport',
          Class: 'walker',
          Passengers: '0' },
        { Name: 'Storm IV Twin-Pod cloud car',
          Model: 'Storm IV Twin-Pod',
          Class: 'repulsorcraft',
          Passengers: '0' },
        { Name: 'Sail barge',
          Model: 'Modified Luxury Sail Barge',
          Class: 'sail barge',
          Passengers: '500' },
        { Name: 'Bantha-II cargo skiff',
          Model: 'Bantha-II',
          Class: 'repulsorcraft cargo skiff',
          Passengers: '16' },
        { Name: 'TIE/IN interceptor',
          Model: 'Twin Ion Engine Interceptor',
          Class: 'starfighter',
          Passengers: '0' },
        { Name: 'Imperial Speeder Bike',
          Model: '74-Z speeder bike',
          Class: 'speeder',
          Passengers: '1' },
        { Name: 'Vulture Droid',
          Model: 'Vulture-class droid starfighter',
          Class: 'starfighter',
          Passengers: '0' },
        { Name: 'Multi-Troop Transport',
          Model: 'Multi-Troop Transport',
          Class: 'repulsorcraft',
          Passengers: '112' },
        { Name: 'Armored Assault Tank',
          Model: 'Armoured Assault Tank',
          Class: 'repulsorcraft',
          Passengers: '6' },
        { Name: 'Single Trooper Aerial Platform',
          Model: 'Single Trooper Aerial Platform',
          Class: 'repulsorcraft',
          Passengers: '0' },
        { Name: 'C-9979 landing craft',
          Model: 'C-9979 landing craft',
          Class: 'landing craft',
          Passengers: '284' },
        { Name: 'Tribubble bongo',
          Model: 'Tribubble bongo',
          Class: 'submarine',
          Passengers: '2' },
        { Name: 'Sith speeder',
          Model: 'FC-20 speeder bike',
          Class: 'speeder',
          Passengers: '0' },
        { Name: 'Zephyr-G swoop bike',
          Model: 'Zephyr-G swoop bike',
          Class: 'repulsorcraft',
          Passengers: '1' },
        { Name: 'Koro-2 Exodrive airspeeder',
          Model: 'Koro-2 Exodrive airspeeder',
          Class: 'airspeeder',
          Passengers: '1' },
        { Name: 'XJ-6 airspeeder',
          Model: 'XJ-6 airspeeder',
          Class: 'airspeeder',
          Passengers: '1' },
        { Name: 'LAAT/i',
          Model: 'Low Altitude Assault Transport/infrantry',
          Class: 'gunship',
          Passengers: '30' },
        { Name: 'LAAT/c',
          Model: 'Low Altitude Assault Transport/carrier',
          Class: 'gunship',
          Passengers: '0' },
        { Name: 'Tsmeu-6 personal wheel bike',
          Model: 'Tsmeu-6 personal wheel bike',
          Class: 'wheeled walker',
          Passengers: '1' },
        { Name: 'Emergency Firespeeder',
          Model: 'Fire suppression speeder',
          Class: 'fire suppression ship',
          Passengers: 'unknown' },
        { Name: 'Droid tri-fighter',
          Model: 'tri-fighter',
          Class: 'droid starfighter',
          Passengers: '0' },
        { Name: 'Oevvaor jet catamaran',
          Model: 'Oevvaor jet catamaran',
          Class: 'airspeeder',
          Passengers: '2' },
        { Name: 'Raddaugh Gnasp fluttercraft',
          Model: 'Raddaugh Gnasp fluttercraft',
          Class: 'air speeder',
          Passengers: '0' },
        { Name: 'Clone turbo tank',
          Model: 'HAVw A6 Juggernaut',
          Class: 'wheeled walker',
          Passengers: '300' },
        { Name: 'Corporate Alliance tank droid',
          Model: 'NR-N99 Persuader-class droid enforcer',
          Class: 'droid tank',
          Passengers: '4' },
        { Name: 'Droid gunship',
          Model: 'HMP droid gunship',
          Class: 'airspeeder',
          Passengers: '0' },
        { Name: 'AT-RT',
          Model: 'All Terrain Recon Transport',
          Class: 'walker',
          Passengers: '0' },
        { Name: 'AT-TE',
          Model: 'All Terrain Tactical Enforcer',
          Class: 'walker',
          Passengers: '36' },
        { Name: 'SPHA',
          Model: 'Self-Propelled Heavy Artillery',
          Class: 'walker',
          Passengers: '30' },
        { Name: 'Flitknot speeder',
          Model: 'Flitknot speeder',
          Class: 'speeder',
          Passengers: '0' },
        { Name: 'Neimoidian shuttle',
          Model: 'Sheathipede-class transport shuttle',
          Class: 'transport',
          Passengers: '6' },
        { Name: 'Geonosian starfighter',
          Model: 'Nantex-class territorial defense',
          Class: 'starfighter',
          Passengers: '0' } ]
