const halfCleanedSpecies = [ { order: 5, species: 'Hutt' },
        { order: 6, species: 'Yoda\'s species' },
        { order: 7, species: 'Trandoshan' },
        { order: 8, species: 'Mon Calamari' },
        { order: 9, species: 'Ewok' },
        { order: 10, species: 'Sullustan' },
        { order: 11, species: 'Neimodian' },
        { order: 12, species: 'Gungan' },
        { order: 13, species: 'Toydarian' },
        { order: 14, species: 'Dug' },
        { order: 15, species: 'Twi\'lek' },
        { order: 16, species: 'Aleena' },
        { order: 17, species: 'Vulptereen' },
        { order: 18, species: 'Xexto' },
        { order: 19, species: 'Toong' },
        { order: 20, species: 'Cerean' },
        { order: 21, species: 'Nautolan' },
        { order: 22, species: 'Zabrak' },
        { order: 23, species: 'Tholothian' },
        { order: 24, species: 'Iktotchi' },
        { order: 25, species: 'Quermian' },
        { order: 26, species: 'Kel Dor' },
        { order: 27, species: 'Chagrian' },
        { order: 28, species: 'Geonosian' },
        { order: 29, species: 'Mirialan' },
        { order: 30, species: 'Clawdite' },
        { order: 31, species: 'Besalisk' },
        { order: 32, species: 'Kaminoan' },
        { order: 33, species: 'Skakoan' },
        { order: 34, species: 'Muun' },
        { order: 35, species: 'Togruta' },
        { order: 36, species: 'Kaleesh' },
        { order: 37, species: 'Pau\'an' },
        { order: 3, species: 'Wookiee' },
        { order: 2, species: 'Droid' },
        { order: 1, species: 'Human' },
        { order: 4, species: 'Rodian' } ]

export default halfCleanedSpecies
