const cleanedPlanets = [ { Name: 'Tatooine',
          Terrain: 'desert',
          Population: '200000',
          Climate: 'arid',
          Residents:
           [ 'Luke Skywalker',
             'C-3PO',
             'Darth Vader',
             'Owen Lars',
             'Beru Whitesun lars',
             'R5-D4',
             'Biggs Darklighter',
             'Anakin Skywalker',
             'Shmi Skywalker',
             'Cliegg Lars' ] },
        { Name: 'Alderaan',
          Terrain: 'grasslands, mountains',
          Population: '2000000000',
          Climate: 'temperate',
          Residents: [ 'Leia Organa', 'Bail Prestor Organa', 'Raymus Antilles' ] },
        { Name: 'Yavin IV',
          Terrain: 'jungle, rainforests',
          Population: '1000',
          Climate: 'temperate, tropical',
          Residents: [] },
        { Name: 'Hoth',
          Terrain: 'tundra, ice caves, mountain ranges',
          Population: 'unknown',
          Climate: 'frozen',
          Residents: [] },
        { Name: 'Dagobah',
          Terrain: 'swamp, jungles',
          Population: 'unknown',
          Climate: 'murky',
          Residents: [] },
        { Name: 'Bespin',
          Terrain: 'gas giant',
          Population: '6000000',
          Climate: 'temperate',
          Residents: [ 'Lobot' ] },
        { Name: 'Endor',
          Terrain: 'forests, mountains, lakes',
          Population: '30000000',
          Climate: 'temperate',
          Residents: [ 'Wicket Systri Warrick' ] },
        { Name: 'Naboo',
          Terrain: 'grassy hills, swamps, forests, mountains',
          Population: '4500000000',
          Climate: 'temperate',
          Residents:
           [ 'R2-D2',
             'Palpatine',
             'Jar Jar Binks',
             'Roos Tarpals',
             'Rugor Nass',
             'Ric Olié',
             'Quarsh Panaka',
             'Gregar Typho',
             'Cordé',
             'Dormé',
             'Padmé Amidala' ] },
        { Name: 'Coruscant',
          Terrain: 'cityscape, mountains',
          Population: '1000000000000',
          Climate: 'temperate',
          Residents: [ 'Finis Valorum', 'Adi Gallia', 'Jocasta Nu' ] },
        { Name: 'Kamino',
          Terrain: 'ocean',
          Population: '1000000000',
          Climate: 'temperate',
          Residents: [ 'Boba Fett', 'Lama Su', 'Taun We' ] },
        { Name: 'Geonosis',
          Terrain: 'rock, desert, mountain, barren',
          Population: '100000000000',
          Climate: 'temperate, arid',
          Residents: [ 'Poggle the Lesser' ] },
        { Name: 'Utapau',
          Terrain: 'scrublands, savanna, canyons, sinkholes',
          Population: '95000000',
          Climate: 'temperate, arid, windy',
          Residents: [ 'Tion Medon' ] },
        { Name: 'Mustafar',
          Terrain: 'volcanoes, lava rivers, mountains, caves',
          Population: '20000',
          Climate: 'hot',
          Residents: [] },
        { Name: 'Kashyyyk',
          Terrain: 'jungle, forests, lakes, rivers',
          Population: '45000000',
          Climate: 'tropical',
          Residents: [ 'Chewbacca', 'Tarfful' ] },
        { Name: 'Polis Massa',
          Terrain: 'airless asteroid',
          Population: '1000000',
          Climate: 'artificial temperate ',
          Residents: [] },
        { Name: 'Mygeeto',
          Terrain: 'glaciers, mountains, ice canyons',
          Population: '19000000',
          Climate: 'frigid',
          Residents: [] },
        { Name: 'Felucia',
          Terrain: 'fungus forests',
          Population: '8500000',
          Climate: 'hot, humid',
          Residents: [] },
        { Name: 'Cato Neimoidia',
          Terrain: 'mountains, fields, forests, rock arches',
          Population: '10000000',
          Climate: 'temperate, moist',
          Residents: [ 'Nute Gunray' ] },
        { Name: 'Saleucami',
          Terrain: 'caves, desert, mountains, volcanoes',
          Population: '1400000000',
          Climate: 'hot',
          Residents: [] },
        { Name: 'Stewjon',
          Terrain: 'grass',
          Population: 'unknown',
          Climate: 'temperate',
          Residents: [ 'Obi-Wan Kenobi' ] },
        { Name: 'Eriadu',
          Terrain: 'cityscape',
          Population: '22000000000',
          Climate: 'polluted',
          Residents: [ 'Wilhuff Tarkin' ] },
        { Name: 'Corellia',
          Terrain: 'plains, urban, hills, forests',
          Population: '3000000000',
          Climate: 'temperate',
          Residents: [ 'Han Solo', 'Wedge Antilles' ] },
        { Name: 'Rodia',
          Terrain: 'jungles, oceans, urban, swamps',
          Population: '1300000000',
          Climate: 'hot',
          Residents: [ 'Greedo' ] },
        { Name: 'Nal Hutta',
          Terrain: 'urban, oceans, swamps, bogs',
          Population: '7000000000',
          Climate: 'temperate',
          Residents: [ 'Jabba Desilijic Tiure' ] },
        { Name: 'Dantooine',
          Terrain: 'oceans, savannas, mountains, grasslands',
          Population: '1000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Bestine IV',
          Terrain: 'rocky islands, oceans',
          Population: '62000000',
          Climate: 'temperate',
          Residents: [ 'Jek Tono Porkins' ] },
        { Name: 'Ord Mantell',
          Terrain: 'plains, seas, mesas',
          Population: '4000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'unknown',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents:
           [ 'Yoda',
             'IG-88',
             'Arvel Crynyd',
             'Qui-Gon Jinn',
             'R4-P17',
             'Finn',
             'Rey',
             'Poe Dameron',
             'BB8',
             'Captain Phasma' ] },
        { Name: 'Trandosha',
          Terrain: 'mountains, seas, grasslands, deserts',
          Population: '42000000',
          Climate: 'arid',
          Residents: [ 'Bossk' ] },
        { Name: 'Socorro',
          Terrain: 'deserts, mountains',
          Population: '300000000',
          Climate: 'arid',
          Residents: [ 'Lando Calrissian' ] },
        { Name: 'Mon Cala',
          Terrain: 'oceans, reefs, islands',
          Population: '27000000000',
          Climate: 'temperate',
          Residents: [ 'Ackbar' ] },
        { Name: 'Chandrila',
          Terrain: 'plains, forests',
          Population: '1200000000',
          Climate: 'temperate',
          Residents: [ 'Mon Mothma' ] },
        { Name: 'Sullust',
          Terrain: 'mountains, volcanoes, rocky deserts',
          Population: '18500000000',
          Climate: 'superheated',
          Residents: [ 'Nien Nunb' ] },
        { Name: 'Toydaria',
          Terrain: 'swamps, lakes',
          Population: '11000000',
          Climate: 'temperate',
          Residents: [ 'Watto' ] },
        { Name: 'Malastare',
          Terrain: 'swamps, deserts, jungles, mountains',
          Population: '2000000000',
          Climate: 'arid, temperate, tropical',
          Residents: [ 'Sebulba' ] },
        { Name: 'Dathomir',
          Terrain: 'forests, deserts, savannas',
          Population: '5200',
          Climate: 'temperate',
          Residents: [ 'Darth Maul' ] },
        { Name: 'Ryloth',
          Terrain: 'mountains, valleys, deserts, tundra',
          Population: '1500000000',
          Climate: 'temperate, arid, subartic',
          Residents: [ 'Bib Fortuna', 'Ayla Secura' ] },
        { Name: 'Aleen Minor',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Ratts Tyerell' ] },
        { Name: 'Vulpter',
          Terrain: 'urban, barren',
          Population: '421000000',
          Climate: 'temperate, artic',
          Residents: [ 'Dud Bolt' ] },
        { Name: 'Troiken',
          Terrain: 'desert, tundra, rainforests, mountains',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Gasgano' ] },
        { Name: 'Tund',
          Terrain: 'barren, ash',
          Population: '0',
          Climate: 'unknown',
          Residents: [ 'Ben Quadinaros' ] },
        { Name: 'Haruun Kal',
          Terrain: 'toxic cloudsea, plateaus, volcanoes',
          Population: '705300',
          Climate: 'temperate',
          Residents: [ 'Mace Windu' ] },
        { Name: 'Cerea',
          Terrain: 'verdant',
          Population: '450000000',
          Climate: 'temperate',
          Residents: [ 'Ki-Adi-Mundi' ] },
        { Name: 'Glee Anselm',
          Terrain: 'lakes, islands, swamps, seas',
          Population: '500000000',
          Climate: 'tropical, temperate',
          Residents: [ 'Kit Fisto' ] },
        { Name: 'Iridonia',
          Terrain: 'rocky canyons, acid pools',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Eeth Koth' ] },
        { Name: 'Tholoth',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Iktotch',
          Terrain: 'rocky',
          Population: 'unknown',
          Climate: 'arid, rocky, windy',
          Residents: [ 'Saesee Tiin' ] },
        { Name: 'Quermia',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Yarael Poof' ] },
        { Name: 'Dorin',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'temperate',
          Residents: [ 'Plo Koon' ] },
        { Name: 'Champala',
          Terrain: 'oceans, rainforests, plateaus',
          Population: '3500000000',
          Climate: 'temperate',
          Residents: [ 'Mas Amedda' ] },
        { Name: 'Mirial',
          Terrain: 'deserts',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Luminara Unduli', 'Barriss Offee' ] },
        { Name: 'Serenno',
          Terrain: 'rainforests, rivers, mountains',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Dooku' ] },
        { Name: 'Concord Dawn',
          Terrain: 'jungles, forests, deserts',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Jango Fett' ] },
        { Name: 'Zolan',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Zam Wesell' ] },
        { Name: 'Ojom',
          Terrain: 'oceans, glaciers',
          Population: '500000000',
          Climate: 'frigid',
          Residents: [ 'Dexter Jettster' ] },
        { Name: 'Skako',
          Terrain: 'urban, vines',
          Population: '500000000000',
          Climate: 'temperate',
          Residents: [ 'Wat Tambor' ] },
        { Name: 'Muunilinst',
          Terrain: 'plains, forests, hills, mountains',
          Population: '5000000000',
          Climate: 'temperate',
          Residents: [ 'San Hill' ] },
        { Name: 'Shili',
          Terrain: 'cities, savannahs, seas, plains',
          Population: 'unknown',
          Climate: 'temperate',
          Residents: [ 'Shaak Ti' ] },
        { Name: 'Kalee',
          Terrain: 'rainforests, cliffs, canyons, seas',
          Population: '4000000000',
          Climate: 'arid, temperate, tropical',
          Residents: [ 'Grievous' ] },
        { Name: 'Umbara',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [ 'Sly Moore' ] },
        { Name: 'Tatooine',
          Terrain: 'desert',
          Population: '200000',
          Climate: 'arid',
          Residents: [] },
        { Name: 'Jakku',
          Terrain: 'deserts',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] } ]

export default cleanedPlanets
