const halfCleanedPlanets = [ { Name: 'Tatooine',
          Terrain: 'desert',
          Population: '200000',
          Climate: 'arid',
          Residents: [] },
        { Name: 'Alderaan',
          Terrain: 'grasslands, mountains',
          Population: '2000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Yavin IV',
          Terrain: 'jungle, rainforests',
          Population: '1000',
          Climate: 'temperate, tropical',
          Residents: [] },
        { Name: 'Hoth',
          Terrain: 'tundra, ice caves, mountain ranges',
          Population: 'unknown',
          Climate: 'frozen',
          Residents: [] },
        { Name: 'Dagobah',
          Terrain: 'swamp, jungles',
          Population: 'unknown',
          Climate: 'murky',
          Residents: [] },
        { Name: 'Bespin',
          Terrain: 'gas giant',
          Population: '6000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Endor',
          Terrain: 'forests, mountains, lakes',
          Population: '30000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Naboo',
          Terrain: 'grassy hills, swamps, forests, mountains',
          Population: '4500000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Coruscant',
          Terrain: 'cityscape, mountains',
          Population: '1000000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Kamino',
          Terrain: 'ocean',
          Population: '1000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Geonosis',
          Terrain: 'rock, desert, mountain, barren',
          Population: '100000000000',
          Climate: 'temperate, arid',
          Residents: [] },
        { Name: 'Utapau',
          Terrain: 'scrublands, savanna, canyons, sinkholes',
          Population: '95000000',
          Climate: 'temperate, arid, windy',
          Residents: [] },
        { Name: 'Mustafar',
          Terrain: 'volcanoes, lava rivers, mountains, caves',
          Population: '20000',
          Climate: 'hot',
          Residents: [] },
        { Name: 'Kashyyyk',
          Terrain: 'jungle, forests, lakes, rivers',
          Population: '45000000',
          Climate: 'tropical',
          Residents: [] },
        { Name: 'Polis Massa',
          Terrain: 'airless asteroid',
          Population: '1000000',
          Climate: 'artificial temperate ',
          Residents: [] },
        { Name: 'Mygeeto',
          Terrain: 'glaciers, mountains, ice canyons',
          Population: '19000000',
          Climate: 'frigid',
          Residents: [] },
        { Name: 'Felucia',
          Terrain: 'fungus forests',
          Population: '8500000',
          Climate: 'hot, humid',
          Residents: [] },
        { Name: 'Cato Neimoidia',
          Terrain: 'mountains, fields, forests, rock arches',
          Population: '10000000',
          Climate: 'temperate, moist',
          Residents: [] },
        { Name: 'Saleucami',
          Terrain: 'caves, desert, mountains, volcanoes',
          Population: '1400000000',
          Climate: 'hot',
          Residents: [] },
        { Name: 'Stewjon',
          Terrain: 'grass',
          Population: 'unknown',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Eriadu',
          Terrain: 'cityscape',
          Population: '22000000000',
          Climate: 'polluted',
          Residents: [] },
        { Name: 'Corellia',
          Terrain: 'plains, urban, hills, forests',
          Population: '3000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Rodia',
          Terrain: 'jungles, oceans, urban, swamps',
          Population: '1300000000',
          Climate: 'hot',
          Residents: [] },
        { Name: 'Nal Hutta',
          Terrain: 'urban, oceans, swamps, bogs',
          Population: '7000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Dantooine',
          Terrain: 'oceans, savannas, mountains, grasslands',
          Population: '1000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Bestine IV',
          Terrain: 'rocky islands, oceans',
          Population: '62000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Ord Mantell',
          Terrain: 'plains, seas, mesas',
          Population: '4000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'unknown',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Trandosha',
          Terrain: 'mountains, seas, grasslands, deserts',
          Population: '42000000',
          Climate: 'arid',
          Residents: [] },
        { Name: 'Socorro',
          Terrain: 'deserts, mountains',
          Population: '300000000',
          Climate: 'arid',
          Residents: [] },
        { Name: 'Mon Cala',
          Terrain: 'oceans, reefs, islands',
          Population: '27000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Chandrila',
          Terrain: 'plains, forests',
          Population: '1200000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Sullust',
          Terrain: 'mountains, volcanoes, rocky deserts',
          Population: '18500000000',
          Climate: 'superheated',
          Residents: [] },
        { Name: 'Toydaria',
          Terrain: 'swamps, lakes',
          Population: '11000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Malastare',
          Terrain: 'swamps, deserts, jungles, mountains',
          Population: '2000000000',
          Climate: 'arid, temperate, tropical',
          Residents: [] },
        { Name: 'Dathomir',
          Terrain: 'forests, deserts, savannas',
          Population: '5200',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Ryloth',
          Terrain: 'mountains, valleys, deserts, tundra',
          Population: '1500000000',
          Climate: 'temperate, arid, subartic',
          Residents: [] },
        { Name: 'Aleen Minor',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Vulpter',
          Terrain: 'urban, barren',
          Population: '421000000',
          Climate: 'temperate, artic',
          Residents: [] },
        { Name: 'Troiken',
          Terrain: 'desert, tundra, rainforests, mountains',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Tund',
          Terrain: 'barren, ash',
          Population: '0',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Haruun Kal',
          Terrain: 'toxic cloudsea, plateaus, volcanoes',
          Population: '705300',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Cerea',
          Terrain: 'verdant',
          Population: '450000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Glee Anselm',
          Terrain: 'lakes, islands, swamps, seas',
          Population: '500000000',
          Climate: 'tropical, temperate',
          Residents: [] },
        { Name: 'Iridonia',
          Terrain: 'rocky canyons, acid pools',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Tholoth',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Iktotch',
          Terrain: 'rocky',
          Population: 'unknown',
          Climate: 'arid, rocky, windy',
          Residents: [] },
        { Name: 'Quermia',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Dorin',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Champala',
          Terrain: 'oceans, rainforests, plateaus',
          Population: '3500000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Mirial',
          Terrain: 'deserts',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Serenno',
          Terrain: 'rainforests, rivers, mountains',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Concord Dawn',
          Terrain: 'jungles, forests, deserts',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Zolan',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Ojom',
          Terrain: 'oceans, glaciers',
          Population: '500000000',
          Climate: 'frigid',
          Residents: [] },
        { Name: 'Skako',
          Terrain: 'urban, vines',
          Population: '500000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Muunilinst',
          Terrain: 'plains, forests, hills, mountains',
          Population: '5000000000',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Shili',
          Terrain: 'cities, savannahs, seas, plains',
          Population: 'unknown',
          Climate: 'temperate',
          Residents: [] },
        { Name: 'Kalee',
          Terrain: 'rainforests, cliffs, canyons, seas',
          Population: '4000000000',
          Climate: 'arid, temperate, tropical',
          Residents: [] },
        { Name: 'Umbara',
          Terrain: 'unknown',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] },
        { Name: 'Tatooine',
          Terrain: 'desert',
          Population: '200000',
          Climate: 'arid',
          Residents: [] },
        { Name: 'Jakku',
          Terrain: 'deserts',
          Population: 'unknown',
          Climate: 'unknown',
          Residents: [] } ]

export default halfCleanedPlanets
