const cleanedPeople = [ { Name: 'Luke Skywalker',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'C-3PO',
          Homeworld: 'Tatooine',
          Species: 'Droid',
          Population: '200000' },
        { Name: 'R2-D2',
          Homeworld: 'Naboo',
          Species: 'Droid',
          Population: '4500000000' },
        { Name: 'Darth Vader',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'Leia Organa',
          Homeworld: 'Alderaan',
          Species: 'Human',
          Population: '2000000000' },
        { Name: 'Owen Lars',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'Beru Whitesun lars',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'R5-D4',
          Homeworld: 'Tatooine',
          Species: 'Droid',
          Population: '200000' },
        { Name: 'Biggs Darklighter',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'Obi-Wan Kenobi',
          Homeworld: 'Stewjon',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'Anakin Skywalker',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'Wilhuff Tarkin',
          Homeworld: 'Eriadu',
          Species: 'Human',
          Population: '22000000000' },
        { Name: 'Chewbacca',
          Homeworld: 'Kashyyyk',
          Species: 'Wookiee',
          Population: '45000000' },
        { Name: 'Han Solo',
          Homeworld: 'Corellia',
          Species: 'Human',
          Population: '3000000000' },
        { Name: 'Greedo',
          Homeworld: 'Rodia',
          Species: 'Rodian',
          Population: '1300000000' },
        { Name: 'Jabba Desilijic Tiure',
          Homeworld: 'Nal Hutta',
          Species: 'Hutt',
          Population: '7000000000' },
        { Name: 'Wedge Antilles',
          Homeworld: 'Corellia',
          Species: 'Human',
          Population: '3000000000' },
        { Name: 'Jek Tono Porkins',
          Homeworld: 'Bestine IV',
          Species: 'Human',
          Population: '62000000' },
        { Name: 'Yoda',
          Homeworld: 'unknown',
          Species: 'Yoda\'s species',
          Population: 'unknown' },
        { Name: 'Palpatine',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000' },
        { Name: 'Boba Fett',
          Homeworld: 'Kamino',
          Species: 'Human',
          Population: '1000000000' },
        { Name: 'IG-88',
          Homeworld: 'unknown',
          Species: 'Droid',
          Population: 'unknown' },
        { Name: 'Bossk',
          Homeworld: 'Trandosha',
          Species: 'Trandoshan',
          Population: '42000000' },
        { Name: 'Lando Calrissian',
          Homeworld: 'Socorro',
          Species: 'Human',
          Population: '300000000' },
        { Name: 'Lobot',
          Homeworld: 'Bespin',
          Species: 'Human',
          Population: '6000000' },
        { Name: 'Ackbar',
          Homeworld: 'Mon Cala',
          Species: 'Mon Calamari',
          Population: '27000000000' },
        { Name: 'Mon Mothma',
          Homeworld: 'Chandrila',
          Species: 'Human',
          Population: '1200000000' },
        { Name: 'Arvel Crynyd',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'Wicket Systri Warrick',
          Homeworld: 'Endor',
          Species: 'Ewok',
          Population: '30000000' },
        { Name: 'Nien Nunb',
          Homeworld: 'Sullust',
          Species: 'Sullustan',
          Population: '18500000000' },
        { Name: 'Qui-Gon Jinn',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'Nute Gunray',
          Homeworld: 'Cato Neimoidia',
          Species: 'Neimodian',
          Population: '10000000' },
        { Name: 'Finis Valorum',
          Homeworld: 'Coruscant',
          Species: 'Human',
          Population: '1000000000000' },
        { Name: 'Jar Jar Binks',
          Homeworld: 'Naboo',
          Species: 'Gungan',
          Population: '4500000000' },
        { Name: 'Roos Tarpals',
          Homeworld: 'Naboo',
          Species: 'Gungan',
          Population: '4500000000' },
        { Name: 'Rugor Nass',
          Homeworld: 'Naboo',
          Species: 'Gungan',
          Population: '4500000000' },
        { Name: 'Ric Olié',
          Homeworld: 'Naboo',
          Species: undefined,
          Population: '4500000000' },
        { Name: 'Watto',
          Homeworld: 'Toydaria',
          Species: 'Toydarian',
          Population: '11000000' },
        { Name: 'Sebulba',
          Homeworld: 'Malastare',
          Species: 'Dug',
          Population: '2000000000' },
        { Name: 'Quarsh Panaka',
          Homeworld: 'Naboo',
          Species: undefined,
          Population: '4500000000' },
        { Name: 'Shmi Skywalker',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'Darth Maul',
          Homeworld: 'Dathomir',
          Species: 'Zabrak',
          Population: '5200' },
        { Name: 'Bib Fortuna',
          Homeworld: 'Ryloth',
          Species: 'Twi\'lek',
          Population: '1500000000' },
        { Name: 'Ayla Secura',
          Homeworld: 'Ryloth',
          Species: 'Twi\'lek',
          Population: '1500000000' },
        { Name: 'Dud Bolt',
          Homeworld: 'Vulpter',
          Species: 'Vulptereen',
          Population: '421000000' },
        { Name: 'Gasgano',
          Homeworld: 'Troiken',
          Species: 'Xexto',
          Population: 'unknown' },
        { Name: 'Ben Quadinaros',
          Homeworld: 'Tund',
          Species: 'Toong',
          Population: '0' },
        { Name: 'Mace Windu',
          Homeworld: 'Haruun Kal',
          Species: 'Human',
          Population: '705300' },
        { Name: 'Ki-Adi-Mundi',
          Homeworld: 'Cerea',
          Species: 'Cerean',
          Population: '450000000' },
        { Name: 'Kit Fisto',
          Homeworld: 'Glee Anselm',
          Species: 'Nautolan',
          Population: '500000000' },
        { Name: 'Eeth Koth',
          Homeworld: 'Iridonia',
          Species: 'Zabrak',
          Population: 'unknown' },
        { Name: 'Adi Gallia',
          Homeworld: 'Coruscant',
          Species: 'Tholothian',
          Population: '1000000000000' },
        { Name: 'Saesee Tiin',
          Homeworld: 'Iktotch',
          Species: 'Iktotchi',
          Population: 'unknown' },
        { Name: 'Yarael Poof',
          Homeworld: 'Quermia',
          Species: 'Quermian',
          Population: 'unknown' },
        { Name: 'Plo Koon',
          Homeworld: 'Dorin',
          Species: 'Kel Dor',
          Population: 'unknown' },
        { Name: 'Mas Amedda',
          Homeworld: 'Champala',
          Species: 'Chagrian',
          Population: '3500000000' },
        { Name: 'Gregar Typho',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000' },
        { Name: 'Cordé',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000' },
        { Name: 'Cliegg Lars',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000' },
        { Name: 'Poggle the Lesser',
          Homeworld: 'Geonosis',
          Species: 'Geonosian',
          Population: '100000000000' },
        { Name: 'Luminara Unduli',
          Homeworld: 'Mirial',
          Species: 'Mirialan',
          Population: 'unknown' },
        { Name: 'Barriss Offee',
          Homeworld: 'Mirial',
          Species: 'Mirialan',
          Population: 'unknown' },
        { Name: 'Dormé',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000' },
        { Name: 'Dooku',
          Homeworld: 'Serenno',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'Bail Prestor Organa',
          Homeworld: 'Alderaan',
          Species: 'Human',
          Population: '2000000000' },
        { Name: 'Jango Fett',
          Homeworld: 'Concord Dawn',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'Zam Wesell',
          Homeworld: 'Zolan',
          Species: 'Clawdite',
          Population: 'unknown' },
        { Name: 'Dexter Jettster',
          Homeworld: 'Ojom',
          Species: 'Besalisk',
          Population: '500000000' },
        { Name: 'Lama Su',
          Homeworld: 'Kamino',
          Species: 'Kaminoan',
          Population: '1000000000' },
        { Name: 'Taun We',
          Homeworld: 'Kamino',
          Species: 'Kaminoan',
          Population: '1000000000' },
        { Name: 'Jocasta Nu',
          Homeworld: 'Coruscant',
          Species: 'Human',
          Population: '1000000000000' },
        { Name: 'Ratts Tyerell',
          Homeworld: 'Aleen Minor',
          Species: 'Aleena',
          Population: 'unknown' },
        { Name: 'R4-P17',
          Homeworld: 'unknown',
          Species: undefined,
          Population: 'unknown' },
        { Name: 'Wat Tambor',
          Homeworld: 'Skako',
          Species: 'Skakoan',
          Population: '500000000000' },
        { Name: 'San Hill',
          Homeworld: 'Muunilinst',
          Species: 'Muun',
          Population: '5000000000' },
        { Name: 'Shaak Ti',
          Homeworld: 'Shili',
          Species: 'Togruta',
          Population: 'unknown' },
        { Name: 'Grievous',
          Homeworld: 'Kalee',
          Species: 'Kaleesh',
          Population: '4000000000' },
        { Name: 'Tarfful',
          Homeworld: 'Kashyyyk',
          Species: 'Wookiee',
          Population: '45000000' },
        { Name: 'Raymus Antilles',
          Homeworld: 'Alderaan',
          Species: 'Human',
          Population: '2000000000' },
        { Name: 'Sly Moore',
          Homeworld: 'Umbara',
          Species: undefined,
          Population: 'unknown' },
        { Name: 'Tion Medon',
          Homeworld: 'Utapau',
          Species: 'Unknown',
          Population: '95000000' },
        { Name: 'Finn',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'Rey',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'Poe Dameron',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown' },
        { Name: 'BB8',
          Homeworld: 'unknown',
          Species: 'Droid',
          Population: 'unknown' },
        { Name: 'Captain Phasma',
          Homeworld: 'unknown',
          Species: undefined,
          Population: 'unknown' },
        { Name: 'Padmé Amidala',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000' } ]

export default cleanedPeople
