const halfCleanedPeople = [ { Name: 'Luke Skywalker',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'C-3PO',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/2/',
          Population: '' },
        { Name: 'R2-D2',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/2/',
          Population: '' },
        { Name: 'Darth Vader',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Leia Organa',
          Homeworld: 'http://swapi.co/api/planets/2/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Owen Lars',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Beru Whitesun lars',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'R5-D4',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/2/',
          Population: '' },
        { Name: 'Biggs Darklighter',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Obi-Wan Kenobi',
          Homeworld: 'http://swapi.co/api/planets/20/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Anakin Skywalker',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Wilhuff Tarkin',
          Homeworld: 'http://swapi.co/api/planets/21/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Chewbacca',
          Homeworld: 'http://swapi.co/api/planets/14/',
          Species: 'http://swapi.co/api/species/3/',
          Population: '' },
        { Name: 'Han Solo',
          Homeworld: 'http://swapi.co/api/planets/22/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Greedo',
          Homeworld: 'http://swapi.co/api/planets/23/',
          Species: 'http://swapi.co/api/species/4/',
          Population: '' },
        { Name: 'Jabba Desilijic Tiure',
          Homeworld: 'http://swapi.co/api/planets/24/',
          Species: 'http://swapi.co/api/species/5/',
          Population: '' },
        { Name: 'Wedge Antilles',
          Homeworld: 'http://swapi.co/api/planets/22/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Jek Tono Porkins',
          Homeworld: 'http://swapi.co/api/planets/26/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Yoda',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/6/',
          Population: '' },
        { Name: 'Palpatine',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Boba Fett',
          Homeworld: 'http://swapi.co/api/planets/10/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'IG-88',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/2/',
          Population: '' },
        { Name: 'Bossk',
          Homeworld: 'http://swapi.co/api/planets/29/',
          Species: 'http://swapi.co/api/species/7/',
          Population: '' },
        { Name: 'Lando Calrissian',
          Homeworld: 'http://swapi.co/api/planets/30/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Lobot',
          Homeworld: 'http://swapi.co/api/planets/6/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Ackbar',
          Homeworld: 'http://swapi.co/api/planets/31/',
          Species: 'http://swapi.co/api/species/8/',
          Population: '' },
        { Name: 'Mon Mothma',
          Homeworld: 'http://swapi.co/api/planets/32/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Arvel Crynyd',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Wicket Systri Warrick',
          Homeworld: 'http://swapi.co/api/planets/7/',
          Species: 'http://swapi.co/api/species/9/',
          Population: '' },
        { Name: 'Nien Nunb',
          Homeworld: 'http://swapi.co/api/planets/33/',
          Species: 'http://swapi.co/api/species/10/',
          Population: '' },
        { Name: 'Qui-Gon Jinn',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Nute Gunray',
          Homeworld: 'http://swapi.co/api/planets/18/',
          Species: 'http://swapi.co/api/species/11/',
          Population: '' },
        { Name: 'Finis Valorum',
          Homeworld: 'http://swapi.co/api/planets/9/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Jar Jar Binks',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/12/',
          Population: '' },
        { Name: 'Roos Tarpals',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/12/',
          Population: '' },
        { Name: 'Rugor Nass',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/12/',
          Population: '' },
        { Name: 'Ric Olié',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: undefined,
          Population: '' },
        { Name: 'Watto',
          Homeworld: 'http://swapi.co/api/planets/34/',
          Species: 'http://swapi.co/api/species/13/',
          Population: '' },
        { Name: 'Sebulba',
          Homeworld: 'http://swapi.co/api/planets/35/',
          Species: 'http://swapi.co/api/species/14/',
          Population: '' },
        { Name: 'Quarsh Panaka',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: undefined,
          Population: '' },
        { Name: 'Shmi Skywalker',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Darth Maul',
          Homeworld: 'http://swapi.co/api/planets/36/',
          Species: 'http://swapi.co/api/species/22/',
          Population: '' },
        { Name: 'Bib Fortuna',
          Homeworld: 'http://swapi.co/api/planets/37/',
          Species: 'http://swapi.co/api/species/15/',
          Population: '' },
        { Name: 'Ayla Secura',
          Homeworld: 'http://swapi.co/api/planets/37/',
          Species: 'http://swapi.co/api/species/15/',
          Population: '' },
        { Name: 'Dud Bolt',
          Homeworld: 'http://swapi.co/api/planets/39/',
          Species: 'http://swapi.co/api/species/17/',
          Population: '' },
        { Name: 'Gasgano',
          Homeworld: 'http://swapi.co/api/planets/40/',
          Species: 'http://swapi.co/api/species/18/',
          Population: '' },
        { Name: 'Ben Quadinaros',
          Homeworld: 'http://swapi.co/api/planets/41/',
          Species: 'http://swapi.co/api/species/19/',
          Population: '' },
        { Name: 'Mace Windu',
          Homeworld: 'http://swapi.co/api/planets/42/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Ki-Adi-Mundi',
          Homeworld: 'http://swapi.co/api/planets/43/',
          Species: 'http://swapi.co/api/species/20/',
          Population: '' },
        { Name: 'Kit Fisto',
          Homeworld: 'http://swapi.co/api/planets/44/',
          Species: 'http://swapi.co/api/species/21/',
          Population: '' },
        { Name: 'Eeth Koth',
          Homeworld: 'http://swapi.co/api/planets/45/',
          Species: 'http://swapi.co/api/species/22/',
          Population: '' },
        { Name: 'Adi Gallia',
          Homeworld: 'http://swapi.co/api/planets/9/',
          Species: 'http://swapi.co/api/species/23/',
          Population: '' },
        { Name: 'Saesee Tiin',
          Homeworld: 'http://swapi.co/api/planets/47/',
          Species: 'http://swapi.co/api/species/24/',
          Population: '' },
        { Name: 'Yarael Poof',
          Homeworld: 'http://swapi.co/api/planets/48/',
          Species: 'http://swapi.co/api/species/25/',
          Population: '' },
        { Name: 'Plo Koon',
          Homeworld: 'http://swapi.co/api/planets/49/',
          Species: 'http://swapi.co/api/species/26/',
          Population: '' },
        { Name: 'Mas Amedda',
          Homeworld: 'http://swapi.co/api/planets/50/',
          Species: 'http://swapi.co/api/species/27/',
          Population: '' },
        { Name: 'Gregar Typho',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Cordé',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Cliegg Lars',
          Homeworld: 'http://swapi.co/api/planets/1/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Poggle the Lesser',
          Homeworld: 'http://swapi.co/api/planets/11/',
          Species: 'http://swapi.co/api/species/28/',
          Population: '' },
        { Name: 'Luminara Unduli',
          Homeworld: 'http://swapi.co/api/planets/51/',
          Species: 'http://swapi.co/api/species/29/',
          Population: '' },
        { Name: 'Barriss Offee',
          Homeworld: 'http://swapi.co/api/planets/51/',
          Species: 'http://swapi.co/api/species/29/',
          Population: '' },
        { Name: 'Dormé',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Dooku',
          Homeworld: 'http://swapi.co/api/planets/52/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Bail Prestor Organa',
          Homeworld: 'http://swapi.co/api/planets/2/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Jango Fett',
          Homeworld: 'http://swapi.co/api/planets/53/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Zam Wesell',
          Homeworld: 'http://swapi.co/api/planets/54/',
          Species: 'http://swapi.co/api/species/30/',
          Population: '' },
        { Name: 'Dexter Jettster',
          Homeworld: 'http://swapi.co/api/planets/55/',
          Species: 'http://swapi.co/api/species/31/',
          Population: '' },
        { Name: 'Lama Su',
          Homeworld: 'http://swapi.co/api/planets/10/',
          Species: 'http://swapi.co/api/species/32/',
          Population: '' },
        { Name: 'Taun We',
          Homeworld: 'http://swapi.co/api/planets/10/',
          Species: 'http://swapi.co/api/species/32/',
          Population: '' },
        { Name: 'Jocasta Nu',
          Homeworld: 'http://swapi.co/api/planets/9/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Ratts Tyerell',
          Homeworld: 'http://swapi.co/api/planets/38/',
          Species: 'http://swapi.co/api/species/16/',
          Population: '' },
        { Name: 'R4-P17',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: undefined,
          Population: '' },
        { Name: 'Wat Tambor',
          Homeworld: 'http://swapi.co/api/planets/56/',
          Species: 'http://swapi.co/api/species/33/',
          Population: '' },
        { Name: 'San Hill',
          Homeworld: 'http://swapi.co/api/planets/57/',
          Species: 'http://swapi.co/api/species/34/',
          Population: '' },
        { Name: 'Shaak Ti',
          Homeworld: 'http://swapi.co/api/planets/58/',
          Species: 'http://swapi.co/api/species/35/',
          Population: '' },
        { Name: 'Grievous',
          Homeworld: 'http://swapi.co/api/planets/59/',
          Species: 'http://swapi.co/api/species/36/',
          Population: '' },
        { Name: 'Tarfful',
          Homeworld: 'http://swapi.co/api/planets/14/',
          Species: 'http://swapi.co/api/species/3/',
          Population: '' },
        { Name: 'Raymus Antilles',
          Homeworld: 'http://swapi.co/api/planets/2/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Sly Moore',
          Homeworld: 'http://swapi.co/api/planets/60/',
          Species: undefined,
          Population: '' },
        { Name: 'Tion Medon',
          Homeworld: 'http://swapi.co/api/planets/12/',
          Species: 'http://swapi.co/api/species/37/',
          Population: '' },
        { Name: 'Finn',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Rey',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'Poe Dameron',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' },
        { Name: 'BB8',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: 'http://swapi.co/api/species/2/',
          Population: '' },
        { Name: 'Captain Phasma',
          Homeworld: 'http://swapi.co/api/planets/28/',
          Species: undefined,
          Population: '' },
        { Name: 'Padmé Amidala',
          Homeworld: 'http://swapi.co/api/planets/8/',
          Species: 'http://swapi.co/api/species/1/',
          Population: '' } ]

export default halfCleanedPeople
