const mostlyCleanedPeople = [ { Name: 'Luke Skywalker',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'C-3PO',
          Homeworld: 'Tatooine',
          Species: 'Droid',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'R2-D2',
          Homeworld: 'Naboo',
          Species: 'Droid',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Darth Vader',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'Leia Organa',
          Homeworld: 'Alderaan',
          Species: 'Human',
          Population: '2000000000',
          PlanetUrl: 1 },
        { Name: 'Owen Lars',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'Beru Whitesun lars',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'R5-D4',
          Homeworld: 'Tatooine',
          Species: 'Droid',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'Biggs Darklighter',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'Obi-Wan Kenobi',
          Homeworld: 'Stewjon',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 19 },
        { Name: 'Anakin Skywalker',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'Wilhuff Tarkin',
          Homeworld: 'Eriadu',
          Species: 'Human',
          Population: '22000000000',
          PlanetUrl: 20 },
        { Name: 'Chewbacca',
          Homeworld: 'Kashyyyk',
          Species: 'Wookiee',
          Population: '45000000',
          PlanetUrl: 13 },
        { Name: 'Han Solo',
          Homeworld: 'Corellia',
          Species: 'Human',
          Population: '3000000000',
          PlanetUrl: 21 },
        { Name: 'Greedo',
          Homeworld: 'Rodia',
          Species: 'Rodian',
          Population: '1300000000',
          PlanetUrl: 22 },
        { Name: 'Jabba Desilijic Tiure',
          Homeworld: 'Nal Hutta',
          Species: 'Hutt',
          Population: '7000000000',
          PlanetUrl: 23 },
        { Name: 'Wedge Antilles',
          Homeworld: 'Corellia',
          Species: 'Human',
          Population: '3000000000',
          PlanetUrl: 21 },
        { Name: 'Jek Tono Porkins',
          Homeworld: 'Bestine IV',
          Species: 'Human',
          Population: '62000000',
          PlanetUrl: 25 },
        { Name: 'Yoda',
          Homeworld: 'unknown',
          Species: 'Yoda\'s species',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Palpatine',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Boba Fett',
          Homeworld: 'Kamino',
          Species: 'Human',
          Population: '1000000000',
          PlanetUrl: 9 },
        { Name: 'IG-88',
          Homeworld: 'unknown',
          Species: 'Droid',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Bossk',
          Homeworld: 'Trandosha',
          Species: 'Trandoshan',
          Population: '42000000',
          PlanetUrl: 28 },
        { Name: 'Lando Calrissian',
          Homeworld: 'Socorro',
          Species: 'Human',
          Population: '300000000',
          PlanetUrl: 29 },
        { Name: 'Lobot',
          Homeworld: 'Bespin',
          Species: 'Human',
          Population: '6000000',
          PlanetUrl: 5 },
        { Name: 'Ackbar',
          Homeworld: 'Mon Cala',
          Species: 'Mon Calamari',
          Population: '27000000000',
          PlanetUrl: 30 },
        { Name: 'Mon Mothma',
          Homeworld: 'Chandrila',
          Species: 'Human',
          Population: '1200000000',
          PlanetUrl: 31 },
        { Name: 'Arvel Crynyd',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Wicket Systri Warrick',
          Homeworld: 'Endor',
          Species: 'Ewok',
          Population: '30000000',
          PlanetUrl: 6 },
        { Name: 'Nien Nunb',
          Homeworld: 'Sullust',
          Species: 'Sullustan',
          Population: '18500000000',
          PlanetUrl: 32 },
        { Name: 'Qui-Gon Jinn',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Nute Gunray',
          Homeworld: 'Cato Neimoidia',
          Species: 'Neimodian',
          Population: '10000000',
          PlanetUrl: 17 },
        { Name: 'Finis Valorum',
          Homeworld: 'Coruscant',
          Species: 'Human',
          Population: '1000000000000',
          PlanetUrl: 8 },
        { Name: 'Jar Jar Binks',
          Homeworld: 'Naboo',
          Species: 'Gungan',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Roos Tarpals',
          Homeworld: 'Naboo',
          Species: 'Gungan',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Rugor Nass',
          Homeworld: 'Naboo',
          Species: 'Gungan',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Ric Olié',
          Homeworld: 'Naboo',
          Species: undefined,
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Watto',
          Homeworld: 'Toydaria',
          Species: 'Toydarian',
          Population: '11000000',
          PlanetUrl: 33 },
        { Name: 'Sebulba',
          Homeworld: 'Malastare',
          Species: 'Dug',
          Population: '2000000000',
          PlanetUrl: 34 },
        { Name: 'Quarsh Panaka',
          Homeworld: 'Naboo',
          Species: undefined,
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Shmi Skywalker',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'Darth Maul',
          Homeworld: 'Dathomir',
          Species: 'Zabrak',
          Population: '5200',
          PlanetUrl: 35 },
        { Name: 'Bib Fortuna',
          Homeworld: 'Ryloth',
          Species: 'Twi\'lek',
          Population: '1500000000',
          PlanetUrl: 36 },
        { Name: 'Ayla Secura',
          Homeworld: 'Ryloth',
          Species: 'Twi\'lek',
          Population: '1500000000',
          PlanetUrl: 36 },
        { Name: 'Dud Bolt',
          Homeworld: 'Vulpter',
          Species: 'Vulptereen',
          Population: '421000000',
          PlanetUrl: 38 },
        { Name: 'Gasgano',
          Homeworld: 'Troiken',
          Species: 'Xexto',
          Population: 'unknown',
          PlanetUrl: 39 },
        { Name: 'Ben Quadinaros',
          Homeworld: 'Tund',
          Species: 'Toong',
          Population: '0',
          PlanetUrl: 40 },
        { Name: 'Mace Windu',
          Homeworld: 'Haruun Kal',
          Species: 'Human',
          Population: '705300',
          PlanetUrl: 41 },
        { Name: 'Ki-Adi-Mundi',
          Homeworld: 'Cerea',
          Species: 'Cerean',
          Population: '450000000',
          PlanetUrl: 42 },
        { Name: 'Kit Fisto',
          Homeworld: 'Glee Anselm',
          Species: 'Nautolan',
          Population: '500000000',
          PlanetUrl: 43 },
        { Name: 'Eeth Koth',
          Homeworld: 'Iridonia',
          Species: 'Zabrak',
          Population: 'unknown',
          PlanetUrl: 44 },
        { Name: 'Adi Gallia',
          Homeworld: 'Coruscant',
          Species: 'Tholothian',
          Population: '1000000000000',
          PlanetUrl: 8 },
        { Name: 'Saesee Tiin',
          Homeworld: 'Iktotch',
          Species: 'Iktotchi',
          Population: 'unknown',
          PlanetUrl: 46 },
        { Name: 'Yarael Poof',
          Homeworld: 'Quermia',
          Species: 'Quermian',
          Population: 'unknown',
          PlanetUrl: 47 },
        { Name: 'Plo Koon',
          Homeworld: 'Dorin',
          Species: 'Kel Dor',
          Population: 'unknown',
          PlanetUrl: 48 },
        { Name: 'Mas Amedda',
          Homeworld: 'Champala',
          Species: 'Chagrian',
          Population: '3500000000',
          PlanetUrl: 49 },
        { Name: 'Gregar Typho',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Cordé',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Cliegg Lars',
          Homeworld: 'Tatooine',
          Species: 'Human',
          Population: '200000',
          PlanetUrl: 0 },
        { Name: 'Poggle the Lesser',
          Homeworld: 'Geonosis',
          Species: 'Geonosian',
          Population: '100000000000',
          PlanetUrl: 10 },
        { Name: 'Luminara Unduli',
          Homeworld: 'Mirial',
          Species: 'Mirialan',
          Population: 'unknown',
          PlanetUrl: 50 },
        { Name: 'Barriss Offee',
          Homeworld: 'Mirial',
          Species: 'Mirialan',
          Population: 'unknown',
          PlanetUrl: 50 },
        { Name: 'Dormé',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000',
          PlanetUrl: 7 },
        { Name: 'Dooku',
          Homeworld: 'Serenno',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 51 },
        { Name: 'Bail Prestor Organa',
          Homeworld: 'Alderaan',
          Species: 'Human',
          Population: '2000000000',
          PlanetUrl: 1 },
        { Name: 'Jango Fett',
          Homeworld: 'Concord Dawn',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 52 },
        { Name: 'Zam Wesell',
          Homeworld: 'Zolan',
          Species: 'Clawdite',
          Population: 'unknown',
          PlanetUrl: 53 },
        { Name: 'Dexter Jettster',
          Homeworld: 'Ojom',
          Species: 'Besalisk',
          Population: '500000000',
          PlanetUrl: 54 },
        { Name: 'Lama Su',
          Homeworld: 'Kamino',
          Species: 'Kaminoan',
          Population: '1000000000',
          PlanetUrl: 9 },
        { Name: 'Taun We',
          Homeworld: 'Kamino',
          Species: 'Kaminoan',
          Population: '1000000000',
          PlanetUrl: 9 },
        { Name: 'Jocasta Nu',
          Homeworld: 'Coruscant',
          Species: 'Human',
          Population: '1000000000000',
          PlanetUrl: 8 },
        { Name: 'Ratts Tyerell',
          Homeworld: 'Aleen Minor',
          Species: 'Aleena',
          Population: 'unknown',
          PlanetUrl: 37 },
        { Name: 'R4-P17',
          Homeworld: 'unknown',
          Species: undefined,
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Wat Tambor',
          Homeworld: 'Skako',
          Species: 'Skakoan',
          Population: '500000000000',
          PlanetUrl: 55 },
        { Name: 'San Hill',
          Homeworld: 'Muunilinst',
          Species: 'Muun',
          Population: '5000000000',
          PlanetUrl: 56 },
        { Name: 'Shaak Ti',
          Homeworld: 'Shili',
          Species: 'Togruta',
          Population: 'unknown',
          PlanetUrl: 57 },
        { Name: 'Grievous',
          Homeworld: 'Kalee',
          Species: 'Kaleesh',
          Population: '4000000000',
          PlanetUrl: 58 },
        { Name: 'Tarfful',
          Homeworld: 'Kashyyyk',
          Species: 'Wookiee',
          Population: '45000000',
          PlanetUrl: 13 },
        { Name: 'Raymus Antilles',
          Homeworld: 'Alderaan',
          Species: 'Human',
          Population: '2000000000',
          PlanetUrl: 1 },
        { Name: 'Sly Moore',
          Homeworld: 'Umbara',
          Species: undefined,
          Population: 'unknown',
          PlanetUrl: 59 },
        { Name: 'Tion Medon',
          Homeworld: 'Utapau',
          Species: 'Unknown',
          Population: '95000000',
          PlanetUrl: 11 },
        { Name: 'Finn',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Rey',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Poe Dameron',
          Homeworld: 'unknown',
          Species: 'Human',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'BB8',
          Homeworld: 'unknown',
          Species: 'Droid',
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Captain Phasma',
          Homeworld: 'unknown',
          Species: undefined,
          Population: 'unknown',
          PlanetUrl: 27 },
        { Name: 'Padmé Amidala',
          Homeworld: 'Naboo',
          Species: 'Human',
          Population: '4500000000',
          PlanetUrl: 7 } ]

export default mostlyCleanedPeople
